In [1]:
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt

In [2]:
logistics = Path(r"..\dataset\raw\Logistics SCM.csv")   # Event Log; ID_Case, Activity, Timestamp

df = pd.read_csv(logistics, sep=",")    # Separate with ; 

print("Event log loaded successfully!")
print("Rows:", len(df))
print("Columns:", len(df.columns))

display(df.head())

Event log loaded successfully!
Rows: 99
Columns: 4

           Case ID  Duration  Expedision Type  Province
0  190710123661H8U      4013                3         2
1  190720055566T5G      6457                3         9
2  19072506336Q7QX      3633                1         5
3  190725102165JA2      6235                1         9
4  19073015476M26F      3955                1         2

In [8]:
print(df.columns.tolist())
print(df.dtypes)

print(f"\nMissing Values: \n{df.isna().sum()}")
display(df.describe().T)

['Case ID', 'Duration', 'Expedision Type', 'Province']
Case ID              str
Duration           int64
Expedision Type    int64
Province           int64
dtype: object

Missing Values:
Case ID            0
Duration           0
Expedision Type    0
Province           0
dtype: int64

,count,mean,std,min,25%,50%,75%,max
Duration,99.0,6744.646465,15896.378845,1458.0,3179.5,4356.0,6346.0,155245.0
Expedision Type,99.0,1.616162,1.184139,1.0,1.0,1.0,2.0,7.0
Province,99.0,3.424242,2.308330,1.0,2.0,3.0,5.0,9.0